services:
  pimcore_container_client:
    class: AzureOss\Storage\Blob\BlobContainerClient
    factory: ['Torq\PimcoreFlysystemAzureBundle\BlobClientFactory', 'createContainerClient']
    arguments:
      $connectionString: 'DefaultEndpointsProtocol=https;AccountName=%env(string:AZURE_STORAGE_ACCOUNT_NAME)%;AccountKey=%env(string:AZURE_STORAGE_ACCOUNT_KEY)%;EndpointSuffix=core.windows.net'
      $containerName: '%env(string:AZURE_STORAGE_ACCOUNT_CONTAINER)%'
  assets_container_client:
    class: AzureOss\Storage\Blob\BlobServiceClient
    factory: ['Torq\PimcoreFlysystemAzureBundle\BlobClientFactory', 'createContainerClient']
    arguments:
      $connectionString: 'DefaultEndpointsProtocol=https;AccountName=%env(string:AZURE_STORAGE_ACCOUNT_NAME)%;AccountKey=%env(string:AZURE_STORAGE_ACCOUNT_KEY)%;EndpointSuffix=core.windows.net'
      $containerName: '%env(string:AZURE_STORAGE_ACCOUNT_CONTAINER_ASSETS)%'

  document_static_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@pimcore_container_client'
      $prefix: 'pages'
  assets_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@assets_container_client'
      $prefix: 'assets'
  asset_cache_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@assets_container_client'
      $prefix: 'asset-cache'
  thumbnail_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@assets_container_client'
      $prefix: 'thumbnails'
  version_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@pimcore_container_client'
      $prefix: 'versions'
  recycle_bin_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@pimcore_container_client'
      $prefix: 'recyclebin'
  admin_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@pimcore_container_client'
      $prefix: 'admin'
  email_log_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@pimcore_container_client'
      $prefix: 'email'
  tmp_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@pimcore_container_client'
      $prefix: 'tmp'
  application_log_adapter:
    class: 'Torq\PimcoreFlysystemAzureBundle\AzureBlobStorageAdapter'
    arguments:
      $containerClient: '@pimcore_container_client'
      $prefix: 'application-log'

